name: Remove Roboshop Infrastructure
on: [workflow_dispatch]
jobs:

  DEV-APPLY:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform destroy
        run: terraform destroy -var-file=env-dev/main.tfvars -auto-approve -var vault_token=${{ secrets.VAULT_TOKEN }}      

  # QA:
  #   runs-on: ubuntu-latest
  #   needs: DEV-APPLY
  #   environment: qa
  #   steps:
  #     - run: echo just a dummy job

  # UAT:
  #   runs-on: ubuntu-latest
  #   needs: QA
  #   environment: uat
  #   steps:
  #     - run: echo just a dummy job  

  # PROD:
  #   runs-on: self-hosted  
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: terraform init -backend-config=env-prod/state.tfvars
  #     - name: Terraform destroy
  #       run: terraform destroy -var-file=env-prod/main.tfvars -auto-approve -var vault_token=${{ secrets.VAULT_TOKEN }}



#       name: ravi
# run-name: pupil
# on: [workflow_dispatch]
# jobs: 
#   my_first: 
#     runs-on: [ubuntu-latest]
#     steps: 
#       - name: Checking Name

#         run: echo dog
#